// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPxkwz-puiKjuSMndKlIa9FjwXdDJzzGg',
    appId: '1:761534087331:web:517da3a67795a59f49bf16',
    messagingSenderId: '761534087331',
    projectId: 'tebak-angka-9058c',
    authDomain: 'tebak-angka-9058c.firebaseapp.com',
    storageBucket: 'tebak-angka-9058c.firebasestorage.app',
    measurementId: 'G-LZDF6NE34T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsKYN84e99NBHEIDZud4eU9LPInrMJdbM',
    appId: '1:761534087331:android:451772334dfe093e49bf16',
    messagingSenderId: '761534087331',
    projectId: 'tebak-angka-9058c',
    storageBucket: 'tebak-angka-9058c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqW3m-RPetQaGbWF3gqVdpG9h8cxGYYc4',
    appId: '1:761534087331:ios:735ffa2ecd2097b749bf16',
    messagingSenderId: '761534087331',
    projectId: 'tebak-angka-9058c',
    storageBucket: 'tebak-angka-9058c.firebasestorage.app',
    iosBundleId: 'com.example.tebakAngkaFlutter',
  );
}
